In [58]:
import pandas as pd
import random

In [59]:
path = "dataset/netflix_final.csv"
file = pd.read_csv(path)
df = pd.DataFrame(file)

display(df)

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,4,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s7,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,1,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
2,s8,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,3,125 min,Dramas,"On a photo shoot in Ghana, an American model s..."
3,s10,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,1,104 min,Comedies,A woman adjusting to life after a loss contend...
4,s13,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,4,127 min,Dramas,After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...
6126,s8802,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,5,96 min,Dramas,Recovering alcoholic Talal wakes up inside a s...
6127,s8803,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,4,158 min,Cult Movies,"A political cartoonist, a crime reporter and a..."
6128,s8805,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,3,88 min,Comedies,Looking to survive in a world taken over by zo...
6129,s8806,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,5,88 min,Children & Family Movies,"Dragged from civilian life, a former superhero..."
6130,s8807,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,1,111 min,Dramas,A scrappy but poor boy worms his way into a ty...

In [60]:
n_lines = 100000

n_filmes = n_lines * 1.5
n_realizador = 20

nome_filme = ["filme" + str(i) for i in range(1, int(n_filmes))]
nome_realizador = ["realizador" + str(i) for i in range(1, n_realizador)]
tipo_genero = df["listed_in"].unique()

In [61]:
def commun_data(df_aux1, df_aux2):
    array_commun = df_aux1["Filme"].isin(df_aux2["Filme"])
    
    count = array_commun.sum()
    print(count)

In [62]:

def new_dataset():
    df_aux1 = None
    df_aux2 = None
    for i in range(2):
        array_filme = []
        array_realizador = []
        array_duracao = []
        array_genero = []
        array_lancamento = []
        array_rating = []
        for j in range(n_lines):
            while(1):
                f = random.choice(nome_filme)
                if f not in array_filme:
                    array_filme.append(f)
                    break
            array_realizador.append(random.choice(nome_realizador))
            array_duracao.append(str(random.randint(30, 240)) + " min")
            array_genero.append(random.choice(tipo_genero))
            array_lancamento.append(random.randint(1960, 2023))
            array_rating.append(random.randint(1, 5))

        d = {"Filme": array_filme, "Realizador": array_realizador, "Duração": array_duracao, "Género": array_genero, "Ano lançamento": array_lancamento, "Rating": array_rating}
        df_d = pd.DataFrame(d)
        
        if i == 0:
            df_aux1 = df_d
            df_d.to_csv("dataset/PartA/dataset" + str(n_lines)+ ".csv", index=False)
        elif i == 1:
            df_aux2 = df_d
            df_d.to_csv("dataset/PartB/dataset" + str(n_lines)+ ".csv", index=False)
    
    commun_data(df_aux1, df_aux2)


new_dataset()

66504

In [63]:
def subdivide_dataset(path1):
    path = path1 + "dataset100000.csv"
    file = pd.read_csv(path)
    df = pd.DataFrame(file)
    sd = 20000
    for i in range(5):
        df2 = pd.DataFrame(df.head(sd))
        df2.to_csv(path1 + "dataset" + str(sd) + ".csv", index=False)
        sd += 20000

subdivide_dataset("dataset/PartA/")
subdivide_dataset("dataset/PartB/")

In [71]:
patha = "dataset/PartA/dataset20000.csv"
pathb = "dataset/PartB/dataset20000.csv"
filea = pd.read_csv(patha)
dfa = pd.DataFrame(filea)
fileb = pd.read_csv(pathb)
dfb = pd.DataFrame(fileb)
commun_data(dfa, dfb)

2699